src/Entity/Country.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CountryRepository")
 */
class Country
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stat", mappedBy="country", orphanRemoval=true)
     */
    private $stat;

    public function __construct()
    {
        $this->stat = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Stat[]
     */
    public function getStat(): Collection
    {
        return $this->stat;
    }

    public function addStat(Stat $stat): self
    {
        if (!$this->stat->contains($stat)) {
            $this->stat[] = $stat;
            $stat->setCountry($this);
        }

        return $this;
    }

    public function removeStat(Stat $stat): self
    {
        if ($this->stat->contains($stat)) {
            $this->stat->removeElement($stat);
            // set the owning side to null (unless already changed)
            if ($stat->getCountry() === $this) {
                $stat->setCountry(null);
            }
        }

        return $this;
    }

    public function getHealed(){
        $total = 0;
        foreach ($this->getStat() as $stat){
            $total += $stat->getHealed();
        }
        return $total;
    }
    public function getContaminated(){
        $total = 0;
        foreach ($this->getStat() as $stat){
            $total += $stat->getContaminated();
        }
        return $total;
    }
    public function getZombified(){
        $total = 0;
        foreach ($this->getStat() as $stat){
            $total += $stat->getZombified();
        }
        return $total;
    }
}

src/Form/CountryType.php
<?php

namespace App\Form;

use App\Entity\Country;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Country::class,
        ]);
    }
}

src/Controller/CountryController.php
<?php

namespace App\Controller;


use App\Entity\Country;
use App\Form\CountryType;
use App\Repository\CountryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;


class CountryController extends AbstractController
{
    /**
     * @Route("/country", name="country")
     */
    public function index()
    {
        $countries = $this->getDoctrine()->getRepository(Country::class)->findBy([],['name' =>"ASC"]);
        return $this->render('country/index.html.twig', [
            'countries' =>$countries,
        ]);
        
    }
    /**
     * Affiche un pays
     * @Route("/country/{id}", name="country_show", methods={"GET"}, requirements={"id":"\d+"})
     * @param Country $country
     * 
     */
    public function show(Country $country)
    {
        return $this->render('country/show.html.twig', [
            'country' => $country
        ]);
    }

    /**
     * Affiche et  le formulaire de création d'un pays
     * @Route("/country/new", name="country_new", methods={"GET","POST"})
     *@param Country $country
     */
    public function new(Request $request )
    {
    $country = new Country();
    $form = $this->createForm(CountryType::class, $country);
    $form->handleRequest($request);
    if ($form->isSubmitted()) {
        $country = $form->getData();

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($country);
        $entityManager->flush();

        return $this->redirectToRoute('country');
    }

    return $this->render('country/form.html.twig', [
        'form' => $form->createView(),
        
    ]);
    
    }


    /**
     * Affiche et Traite le formulaire d'édition d'un pays (POST) et (GET)
     * 
     * @Route("/country/{id}/edit", name="country_edit", methods={"GET", "POST"})
     * @param Country $country
     */
    public function edit(Country $country)
    {
    }

    /**
     * Supprime un pays
     * @Route("/country/{id}", name="country_delete", methods={"DELETE"})
     * @param Country $country
     */
    public function delete(Country $country)
    {

    }
}

templates/country/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Pays{% endblock %}

{% block body %}
    <div class="container mt-3 text-center">
        <div class="row">
            <div class="col">
                <u><h1 class="m-5">Ajouter un Pays</h1></u>
                <div class="text-center">{{ form_start(form) }} </div>
                {{ form_widget(form) }}
                    <button class="btn btn-danger text-center my-3">Enregister</button>
                {{ form_end(form) }}

            </div>
        </div>
    </div>
{% endblock %}

templates/country/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<section class=" text-center">
    <h1>Pays Infectés<h1></h1>
        {% for country in countries %}
        <div class="container">
            <h4><a href="{{ path ('country_show', {id: country.id}) }}"> {{ country.name }} </a></h4>
            <h6>Cas total Guéris</h6>
            {% if country.healed > country.zombified %}
            <p class="text-center" style="background-color: rgb(16, 202, 16);">{{ country.healed }}</p>
            {% else %}
            <p class="text-center" style="background-color: rgb(255, 38, 38);">{{ country.healed }}</p>
            {% endif %}<br>
        <h6>Cas total Contaminés</h6>
        {{country.contaminated}} <br>
        <h6>Cas total Zombifiés</h6>
        {{country.zombified}} <br>
        </div>
        {% endfor %}
</section>
{% endblock %}

templates/country/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<section class=" text-center">
    <div class="container">
        <h1>Pays Infectés<h1>
                <h2 class="py-4">{{ country.name }} </h2>
                {% for stat in country.stat %}  
                <hr>
                <h5>Les Contaminés</h5>
                {% if stat.healed > stat.zombified %}
            <p class="text-center" style="background-color: rgb(16, 202, 16);">{{ stat.healed }}</p>
            {% else %}
            <p class="text-center" style="background-color: rgb(255, 38, 38);">{{ stat.healed }}</p>
            {% endif %}
                <h5>Les Contaminés</h5>
                {{ stat.contaminated }} <br>
                <h5>Les ZOMBIFIES</h5>
                {{ stat.zombified}} <br>
                <h5>Date d'enregistrement</h5>
                {{stat.statdate|date('d-m-Y')}}
                {% endfor %}
                <hr>
    </div>
</section>
{% endblock %}